AllCops:
    NewCops: enable
    SuggestExtensions: false

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/RaiseArgs:
  EnforcedStyle: compact

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/IfUnlessModifier:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
