#!/usr/bin/env ruby
# frozen_string_literal: true

require "web_function"
require "json"

# Usage:
#   wfn call --auth token endpoint_url key1=value1 [key2=value2 ...]

auth_token = nil
auth_index = ARGV.index("--auth")
if auth_index
  auth_token = ARGV[auth_index + 1]
  ARGV.slice!(auth_index, 2)
end

version = nil
version_index = ARGV.index("--version")
if version_index
  version = ARGV[version_index + 1]
  ARGV.slice!(version_index, 2)
end

command = ARGV[0]

case command
when "call"
  endpoint_url = ARGV[1]
  args = JSON.parse(ARGV[2] || "{}")

  begin
    response = WebFunction::Request.execute(endpoint_url, bearer_auth: auth_token, version: version, args: args)
    puts JSON.pretty_generate(response)
  rescue WebFunction::Error => e
    puts e
    warn "error: [#{e.code}] #{e.message}"
    warn ""
    if e.details
      warn JSON.pretty_generate(e.details).lines.map { |line| "|  #{line}" }.join
    end
    exit 2
  end
else
  warn "Usage:\n  wfn docs package_url endpoint_name\n  wfn call --auth token endpoint_url key1=value1 [key2=value2 ...]"
  exit 1
end
